name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload debug apk
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app-debug
        path: app/build/outputs/apk/debug
        if-no-files-found: error
    
    - name: Sign release apk
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEY_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_PASS }}
        keyPassword: ${{ secrets.KEY_PASS }}
    
    - name: Upload release apk
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app-release
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        if-no-files-found: error
